---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
# clickhouse_version_x86: "22.3.3.44"
# clickhouse_packages_x86:
# clickhouse-common-static
